apiVersion : apps/v1
kind: Deployment
metadata:
  name: waseemspringbootapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waseemspringbootapp
  template:
    metadata:
      labels:
        app: waseemspringbootapp 
    spec:
      containers:
        - name: waseemspringbootapp 
          image: myacrrepo431.azurecr.io/waseemspringbootapp
          ports:
          - containerPort: 80